name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix build
    - run: nix flake check
